2025-03-17 21:24:30,193 INFO    MainThread:3128 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-03-17 21:24:30,207 INFO    MainThread:3128 [wandb_setup.py:_flush():67] Configure stats pid to 3128
2025-03-17 21:24:30,207 INFO    MainThread:3128 [wandb_setup.py:_flush():67] Loading settings from C:\Users\praha\.config\wandb\settings
2025-03-17 21:24:30,208 INFO    MainThread:3128 [wandb_setup.py:_flush():67] Loading settings from C:\Users\praha\Documents\IIT madras\Acads\sem 10\introtoDL\DA6401_A01\wandb\settings
2025-03-17 21:24:30,209 INFO    MainThread:3128 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-17 21:24:30,211 INFO    MainThread:3128 [wandb_init.py:setup_run_log_directory():647] Logging user logs to C:\Users\praha\Documents\IIT madras\Acads\sem 10\introtoDL\DA6401_A01\wandb\run-20250317_212430-rnpt4htx\logs\debug.log
2025-03-17 21:24:30,213 INFO    MainThread:3128 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to C:\Users\praha\Documents\IIT madras\Acads\sem 10\introtoDL\DA6401_A01\wandb\run-20250317_212430-rnpt4htx\logs\debug-internal.log
2025-03-17 21:24:30,213 INFO    MainThread:3128 [wandb_init.py:init():761] calling init triggers
2025-03-17 21:24:30,214 INFO    MainThread:3128 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-17 21:24:30,214 INFO    MainThread:3128 [wandb_init.py:init():784] starting backend
2025-03-17 21:24:30,215 INFO    MainThread:3128 [wandb_init.py:init():788] sending inform_init request
2025-03-17 21:24:30,256 INFO    MainThread:3128 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-03-17 21:24:30,256 INFO    MainThread:3128 [wandb_init.py:init():798] backend started and connected
2025-03-17 21:24:30,259 INFO    MainThread:3128 [wandb_init.py:init():891] updated telemetry
2025-03-17 21:24:30,334 INFO    MainThread:3128 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-03-17 21:24:53,893 ERROR   MainThread:3128 [wandb_init.py:init():1478] error in wandb.init()
Traceback (most recent call last):
  File "c:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_init.py", line 1468, in init
    return wi.init(run_settings, run_config)
  File "c:\Users\praha\miniconda3\envs\DS\lib\site-packages\wandb\sdk\wandb_init.py", line 963, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 401: {"data":{"upsertBucket":null},"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}]}
