{"time":"2025-03-17T22:31:06.7163148+05:30","level":"INFO","msg":"stream: starting","core version":"0.19.8","symlink path":"C:\\Users\\praha\\Documents\\IIT madras\\Acads\\sem 10\\introtoDL\\DA6401_A01\\wandb\\run-20250317_223106-0krau4xo\\logs\\debug-core.log"}
{"time":"2025-03-17T22:31:06.8328143+05:30","level":"INFO","msg":"created new stream","id":"0krau4xo"}
{"time":"2025-03-17T22:31:06.8328143+05:30","level":"INFO","msg":"stream: started","id":"0krau4xo"}
{"time":"2025-03-17T22:31:06.8328143+05:30","level":"INFO","msg":"sender: started","stream_id":"0krau4xo"}
{"time":"2025-03-17T22:31:06.8328143+05:30","level":"INFO","msg":"writer: Do: started","stream_id":"0krau4xo"}
{"time":"2025-03-17T22:31:06.8328143+05:30","level":"INFO","msg":"handler: started","stream_id":"0krau4xo"}
{"time":"2025-03-17T22:31:27.8899459+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:31:51.403891+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:32:16.7686893+05:30","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-03-17T22:32:39.8300501+05:30","level":"INFO","msg":"stream: closing","id":"0krau4xo"}
{"time":"2025-03-17T22:32:39.8301705+05:30","level":"ERROR","msg":"sender: upsertRun:","error":"failed to upsert bucket: api: failed sending: POST https://api.wandb.ai/graphql giving up after 4 attempt(s): context canceled"}
{"time":"2025-03-17T22:32:39.8301705+05:30","level":"INFO","msg":"handler: closed","stream_id":"0krau4xo"}
{"time":"2025-03-17T22:32:39.8301705+05:30","level":"INFO","msg":"writer: Close: closed","stream_id":"0krau4xo"}
{"time":"2025-03-17T22:32:39.8301705+05:30","level":"INFO","msg":"sender: closed","stream_id":"0krau4xo"}
{"time":"2025-03-17T22:32:39.8301705+05:30","level":"WARN","msg":"runwork: ignoring record after close","work":{}}
{"time":"2025-03-17T22:32:39.8313462+05:30","level":"INFO","msg":"stream: closed","id":"0krau4xo"}
